Controllers/ContentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Project.Models;
using System.Security.Claims;

namespace MVC_Project.Controllers
{
    [Authorize(Roles ="user")] 
    public class ContentController : Controller
    {

        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        public ContentController(UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        public IActionResult Details(int id)
        {
            Match match = context.Matches.FirstOrDefault(p => p.Match_Id == id);
            return View(match);
           
        }
       


        AppDbContext context=new AppDbContext();    
       
       
        public IActionResult MatchList()
        {
            var matches = context.Matches.ToList();
            return View(matches);
        }


        public IActionResult BookingDetails(string ticketId)
        {
            var ticket = context.Tickets.Include(t => t.Match)
                .FirstOrDefault(t => t.Ticket_Id == ticketId);

           

            return View(ticket);
        }



       
        public IActionResult BookTicket(int matchId)
        {
            var match = context.Matches.FirstOrDefault(m => m.Match_Id == matchId);

            if ( match.AvailableTickets == 0)
            {
                return NotFound("Match not found or no tickets available");
            }
       
            var ticket = new Ticket
            {
                UserId = GetUserId(),
                MatchId = match.Match_Id,
                
                    Ticket_Id = Guid.NewGuid().ToString(), 
                                                           
                
            };

            match.AvailableTickets -= 1;
            context.Tickets.Add(ticket);
            context.SaveChanges();

            return RedirectToAction("BookingDetails", new { ticketId = ticket.Ticket_Id });
        }

        private string GetUserId()
        {
           
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            if (userIdClaim != null)
            {
                return userIdClaim.Value; 
            }
            throw new Exception("User is not authenticated");
        }
    }
}

Controllers/MyPageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Project.Models;
using System.Security.Claims;

namespace MVC_Project.Controllers
{
    [Authorize(Roles ="user")]
    public class MyPageController : Controller
   

    {
        AppDbContext context = new AppDbContext();

        public IActionResult UserTickets()
        {
          var userId =GetUserId(); 

            var tickets = context.Tickets
                                 .Include(t => t.Match) 

                                 .Where(t => t.UserId == userId)
                                 .ToList();

           

            return View(tickets); 
        }

        private string GetUserId()
        {
            var userIdClaim = User.FindFirst(ClaimTypes.NameIdentifier);
            if (userIdClaim != null)
            {
                return userIdClaim.Value;
            }
            throw new Exception("User is not authenticated");
        }
    }

}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVC_Project.Models;
using MVC_Project.ViewModels;
using System.Security.Claims;

namespace MVC_Project.Controllers
{
    [Authorize(Roles = "admin")]
    public class RoleController : Controller
    {
       
        public UserManager<ApplicationUser> userManager { get; }

       public RoleManager<IdentityRole> roleManager { get; }
        private readonly SignInManager<ApplicationUser> signInManager;
       

        public RoleController(RoleManager<IdentityRole> roleManager, 
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [HttpGet]
        public async Task<IActionResult> AllRoles()
        {
            // Get all roles
            var roles = await roleManager.Roles.ToListAsync();
            return View(roles);
        }

        [HttpGet]

        public IActionResult NewRole()
        {
            return View();
        }
        [HttpPost]

        public async Task<IActionResult> NewRole(RoleViewModel vm)
        {
            if(ModelState.IsValid==true)
            {
                IdentityRole roleModel= new IdentityRole();
                roleModel.Name=vm.RoleName;
                IdentityResult result=await roleManager.CreateAsync(roleModel);
                if(result.Succeeded)
                {
                    return RedirectToAction("Index","Home");
                }
                else
                {
                    foreach(var item in result.Errors)
                    {
                        ModelState.AddModelError("", item.Description); 
                    }
                }
            }
            return View();
        }
        [HttpGet]

        public async Task<IActionResult> AddAdmin()
        {
            return View();
        }

            [HttpPost]
        public async Task<IActionResult> AddAdmin(RegisterViewModel vm)
        {
            if (ModelState.IsValid)
            {//Mapping from vm to model
                ApplicationUser userModel = new ApplicationUser();
                userModel.Email = vm.Email;
                userModel.UserName = vm.UserName;
                userModel.Phone = vm.Phone;
                userModel.PasswordHash = vm.Password;

                IdentityResult result = await userManager.CreateAsync(userModel, vm.Password);
                if (result.Succeeded)
                {
                  await  userManager.AddToRoleAsync(userModel,"admin");
                 
                    List<Claim> claims = new List<Claim>();
                    claims.Add(new Claim(ClaimTypes.Email, userModel.Email));
                    await signInManager.SignInWithClaimsAsync(userModel, false, claims);
                    return RedirectToAction("Index", "Home");

                }
                else
                {
                    foreach (var item in result.Errors)
                    {
                        ModelState.AddModelError("Password", item.Description);
                    }
                }
            }
            return View(vm);
        }


    }   
}


Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Project</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Project.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" 
    integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" 
    referrerpolicy="no-referrer" />
</head>
<body>

       
    </nav>


    <header>


        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-White bg-White border-bottom box-shadow mb-3">
            <div class="container-fluid">
               @*  <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_Project</a> *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("user"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Content" asp-action="MatchList">Matches</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="MyPage" asp-action="UserTickets">MyPage</a>
                            </li>


                        }
                        @if(User.IsInRole("admin"))
                        {
                          <li class="nav-item">
                             <a class="nav-link text-dark"  asp-controller="AdminPanel" asp-action="AdminPanel">Matches</a>
                         </li>
                         
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AdminPanel" asp-action="CreateMatch">Create_Match</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Role" asp-action="AddAdmin">Add_Admin</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Role" asp-action="NewRole">Add_Role</a>
                        </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Role" asp-action="AllRoles">ExistingRoles</a>
                            </li>
                        
                        }
                    </ul>
                    
                    <ul class="navbar-nav flex-grow-1">

                      
                    </ul>
                    <ul class="navbar-nav ">
                        @if (User.Identity.IsAuthenticated==false)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark"  asp-controller="Account" asp-action="Register">
                                    Register <i class="fa-regular fa-registered" style="color:darkblue;font-size:20px"></i>
                                    </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Login">
                                    Login <i class="fa fa-sign-in" aria-hidden="true" style="color:darkblue;font-size:20px"></i>
                                    </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" >Welcome @User.Identity.Name</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Include jQuery and Bootstrap's JS -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>



    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/js/all.min.js" 
    integrity="sha512-6sSYJqDreZRZGkJ3b+YfdhB3MzmuP9R7X1QZ6g5aIXhRvR1Y/N/P47jmnkENm7YL3oqsmI6AK+V6AD99uWDnIw=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>